name: devera_flutter_places_img_labelers_tts_app

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.5
  flutter_spinkit: ^5.1.0

  #fancy_on_boarding: ^1.7.0
  fancy_on_boarding: ^1.8.0-nullsafety.0

  image_picker: ^0.8.5+3
  google_mlkit_image_labeling: ^0.4.0
  provider: ^6.0.3

  # flutter_svg: ^1.1.3
  flutter_svg: ^0.21.0-nullsafety.0
  path_provider: ^2.0.11
  path: ^1.8.1
  animated_text_kit: ^4.2.2

  speech_to_text: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/png/
    - assets/svg/
    - assets/ml/
    - assets/images/

  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunitoSemiBold.ttf
        - asset: assets/fonts/nunitoBold.ttf
          weight: 700
